# Generated by Django 5.2.4 on 2025-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='receitasfotos/'),
        ),
    ]
