# Generated by Django 5.2.4 on 2025-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_receita_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='deslike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receita',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
